package com.acmemail.judah.cartesian_plane.sandbox;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.image.BufferedImage;

import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

/**
 * Encapsulates a simple GUI
 * to display the figure
 * generated by {@linkplain BufferedImagedemo1}.
 * 
 * @author Jack Straub
 * 
 * @see BufferedImagedemo1
 */
public class BufferedImageShowDemo1
{
    /** The width of the GUI's main panel. */
    private static final int    width   = 300;
    /** The height of the GUI's main panel. */
    private static final int    height  = 300;
    
    /**
     * Application entry point.
     *
     * @param args command line arguments, not used
     *
     */
    public static void main(String[] args)
    {
        BufferedImageShowDemo1 demo = new BufferedImageShowDemo1();
        SwingUtilities.invokeLater( () -> demo.showGUI() );
    }
    
    /**
     * Creates the target GUI
     * and makes it visible.
     */
    private void showGUI()
    {
        JFrame  frame   = new JFrame( "Buffered Image Demo GUI" );
        frame.setDefaultCloseOperation( JFrame.EXIT_ON_CLOSE );
        frame.setContentPane( new DemoPanel() );
        frame.setLocation( 200, 200 );
        frame.pack();
        frame.setVisible( true );
    }
    
    /**
     * Encapsulates the main panel
     * displayed in
     * the target GUI.
     * Contains the figure
     * generated by {@linkplain BufferedImageDemo1}.
     * 
     * @author Jack Straub
     */
    @SuppressWarnings("serial")
    private class DemoPanel extends JPanel
    {
        /** The background color of the panel. */
        private static final Color  bgColor = Color.LIGHT_GRAY;
        /** The image generated by {@linkplain BufferedImageDemo1}. */
        private final BufferedImage image;
        
        /**
         * Constructor.
         * Initializes the panel.
         */
        public DemoPanel()
        {
            BufferedImageDemo1  demo    = 
                new BufferedImageDemo1( width, height );
            image = demo.getImage();
            setPreferredSize( new Dimension( width + 100, height + 100 ) );
        }
        
        /**
         * Draws the image
         * generated by {@linkplain BufferedImageDemo1}
         * in the panel.
         */
        @Override
        public void paintComponent( Graphics gtx )
        {
            Color   color   = gtx.getColor();
            /* --- save original color --- */ 
            gtx.setColor( bgColor );
            int width   = getWidth();
            int height  = getHeight();
            gtx.fillRect( 0, 0, width, height );
            /* --- restore original color */ 
            gtx.setColor( color );

            int xco     = width / 2 - image.getWidth() / 2;
            int yco     = height / 2 - image.getHeight() / 2;
            gtx.drawImage( image, xco, yco, this );
        }
    }
}
