// This file generated by LinePropertySetInitializerGenerator
package com.acmemail.judah.cartesian_plane.test_utils;
import static com.acmemail.judah.cartesian_plane.CPConstants.*;
public class LinePropertySetInitializer_orig
{
    // TIC_MAJOR
    public static final String TIC_MAJOR_COLOR = "100";
    public static final String TIC_MAJOR_WEIGHT = "1.1";
    public static final String TIC_MAJOR_LEN = "1.2";
    public static final String TIC_MAJOR_MPU = "1.3";
    public static final String TIC_MAJOR_DRAW = "true";
    // TIC_MINOR
    public static final String TIC_MINOR_COLOR = "110";
    public static final String TIC_MINOR_WEIGHT = "2.1";
    public static final String TIC_MINOR_LEN = "2.2";
    public static final String TIC_MINOR_MPU = "2.3";
    public static final String TIC_MINOR_DRAW = "true";
    // GRID_LINE
    public static final String GRID_LINE_WEIGHT = "3.0";
    public static final String GRID_LINE_LPU = "3.1";
    public static final String GRID_LINE_COLOR = "120";
    public static final String GRID_LINE_DRAW = "true";
    // AXIS
    public static final String AXIS_COLOR = "130";
    public static final String AXIS_WEIGHT = "4.1";

    public static void initProperties()
    {
        System.setProperty( TIC_MAJOR_COLOR_PN, TIC_MAJOR_COLOR );
        System.setProperty( TIC_MAJOR_WEIGHT_PN, TIC_MAJOR_WEIGHT );
        System.setProperty( TIC_MAJOR_LEN_PN, TIC_MAJOR_LEN );
        System.setProperty( TIC_MAJOR_MPU_PN, TIC_MAJOR_MPU );
        System.setProperty( TIC_MAJOR_DRAW_PN, TIC_MAJOR_DRAW );
        System.setProperty( TIC_MINOR_COLOR_PN, TIC_MINOR_COLOR );
        System.setProperty( TIC_MINOR_WEIGHT_PN, TIC_MINOR_WEIGHT );
        System.setProperty( TIC_MINOR_LEN_PN, TIC_MINOR_LEN );
        System.setProperty( TIC_MINOR_MPU_PN, TIC_MINOR_MPU );
        System.setProperty( TIC_MINOR_DRAW_PN, TIC_MINOR_DRAW );
        System.setProperty( GRID_LINE_WEIGHT_PN, GRID_LINE_WEIGHT );
        System.setProperty( GRID_LINE_LPU_PN, GRID_LINE_LPU );
        System.setProperty( GRID_LINE_COLOR_PN, GRID_LINE_COLOR );
        System.setProperty( GRID_LINE_DRAW_PN, GRID_LINE_DRAW );
        System.setProperty( AXIS_COLOR_PN, AXIS_COLOR );
        System.setProperty( AXIS_WEIGHT_PN, AXIS_WEIGHT );
    }
}
